// Turns the website's configuration into files for the Typst compiler:
//   /config/notebook.toml – the same schema that lib/config.typ reads,
//   /main.typ              – an insert assembled from the templates in templates/.
// Text typed by the user (the title) goes through sys.inputs, never into the source.

import { monthAt, parseIsoDate } from './calendar';
import { MAX_STAPLED_SHEETS, type NotebookConfig, type Section } from './config';
import {
  DEFAULT_PRINTER,
  MARKS,
  NUMBER_BOX,
  PAPER_SIZES,
  fitToPrinter,
  sheetLayout,
  type PrinterProfile,
} from './printer';
import { notesPages, weekSpan } from './volume';

export const MAIN_PATH = '/main.typ';
export const CONFIG_PATH = '/config/notebook.toml';

// store names from the shopping list: user text, so through sys.inputs like the title
const STORES_INPUT = 'shopping-stores';
const shoppingStores = (cfg: NotebookConfig): string[] =>
  cfg.sections.find((s) => s.type === 'shopping')?.stores ?? [];
const storesInput = `json(bytes(sys.inputs.at(${JSON.stringify(STORES_INPUT)}, default: "[]")))`;

export interface TypstInput {
  files: Record<string, string>;
  inputs: Record<string, string>;
}

export function toTypst(cfg: NotebookConfig, printer = DEFAULT_PRINTER): TypstInput {
  return {
    files: { [CONFIG_PATH]: toToml(cfg, printer), [MAIN_PATH]: toMain(cfg) },
    inputs: typstInputs(cfg),
  };
}

// user text for sys.inputs
export function typstInputs(cfg: NotebookConfig): Record<string, string> {
  return { title: cfg.title, [STORES_INPUT]: JSON.stringify(shoppingStores(cfg)) };
}

const num = (x: number) => (Number.isInteger(x) ? x.toFixed(1) : String(x));
const str = (s: string) => JSON.stringify(s);

// Page number position: the box centre halfway into the bottom margin, but no closer
// to the edge than half a box above the unprintable area; x aligned to the outer
// margin, also not inside the unprintable area.
export function numberPlacement(cfg: NotebookConfig, unprintable = 0): { x: number; y: number } {
  const half = NUMBER_BOX / 2;
  return {
    x: Math.max(2, unprintable, cfg.margins.outer - 1),
    y: Math.min(Math.max(cfg.margins.bottom / 2, unprintable + half), cfg.margins.bottom - half),
  };
}

// Margins are first fitted to the printer (fitToPrinter), so the checks in
// lib/config.typ (margin and page number outside the unprintable area) pass.
// target 'preview': insert pages only, without the sheet and marks.
// target 'print': a real sheet from the profile, for imposition (impose.typ).
export function toToml(
  cfg: NotebookConfig,
  printer = DEFAULT_PRINTER,
  target: 'preview' | 'print' = 'preview',
): string {
  const fitted = fitToPrinter(cfg, printer).config;
  const layout = sheetLayout(fitted, printer);
  const print = target === 'print';
  const u = printer.unprintable;
  const n = numberPlacement(fitted, u);
  const paper = PAPER_SIZES[printer.paper];
  return `# Generated by the web generator.
${designToml(fitted, 'web', `from_edge_x = ${num(n.x)}\nfrom_edge_y = ${num(n.y)}\n`, print && layout.stacked)}
${
  print
    ? `# Sheet from the printer profile, in landscape (lib/sheet.typ rotates it for stacked).
[printer]
sheet_width = ${num(paper.width)}
sheet_height = ${num(paper.height)}`
    : `# Preview: a large sheet, so that the "format fits on the sheet" check in lib/config.typ
# doesn't block the preview (sheetLayout reports it in the panel).
[printer]
sheet_width = 2000.0
sheet_height = 2000.0`
}
unprintable = ${num(u)}

[duplex]
dx = ${num(printer.dx)}
dy = ${num(printer.dy)}
even_reverse = ${printer.evenReverse}
rotate_back = ${tomlRotateBack(printer, layout.stacked)}
max_sheets = ${MAX_STAPLED_SHEETS}

[marks]
enabled = ${print}
color = "#8a8a8a"
width = 0.2
length = ${num(MARKS.length)}
gap = ${num(MARKS.gap)}
band_start = ${num(layout.bandStart)}
band_length = ${num(MARKS.bandLength)}
`;
}

// lib/sheet.typ rotates the back of a stacked sheet by 180° (back-rotated = rotate_back != stacked),
// because with manual duplex the sheet turns around its short side, and the insert around its spine
// along the long one. With automatic duplex the printer itself flips the sheet around
// the fold (as the wizard instructs), so that rotation doesn't apply. rotateBack in the profile is
// an extra rotation, the same for every format.
export function tomlRotateBack(printer: PrinterProfile, stacked: boolean): boolean {
  return printer.duplex === 'auto' ? printer.rotateBack !== stacked : printer.rotateBack;
}

// Appearance settings shared by the website and the insert for printing. `format` is the format name:
// "web" on the website; in the CLI a preset (regular/passport/pocket), so that stacked works.
function designToml(
  cfg: NotebookConfig,
  format: string,
  numberPlacement: string,
  stacked = false,
): string {
  const { margins: m, grid: g } = cfg;
  const custom = format === 'web' || format === 'custom';
  return `[insert]
format = ${str(format)}
pages = ${insertPages(cfg)}
lang = ${str(cfg.lang)}
${
  custom
    ? `
[formats.${format}]
width = ${num(cfg.format.width)}
height = ${num(cfg.format.height)}
${stacked ? 'stacked = true\n' : ''}`
    : ''
}
[margins]
top = ${num(m.top)}
bottom = ${num(m.bottom)}
inner = ${num(m.inner)}
outer = ${num(m.outer)}

[grid]
type = ${str(g.kind)}
spacing = ${num(g.spacing)}
dot_diameter = ${num(g.dotDiameter)}
line_width = ${num(g.lineWidth)}
color = ${str(g.color)}
accent = ${str(g.accent)}

[ink]
text = "#000000"
line = ${str(cfg.ink.color)}
line_width = 0.15

[font]
family = ${str(cfg.font.family)}
size = ${num(cfg.font.size)}

[page_numbers]
enabled = ${cfg.numbering.enabled}
size = ${num(cfg.numbering.size)}
color = "#000000"
${numberPlacement}position = ${str(cfg.numbering.position)}

[calendar]
year = ${cfg.year}
week_start = ${str(cfg.weekStart)}
`;
}

// An insert for printing from the CLI (`just from-web`): inserts/<name>.typ and inserts/<name>.toml.
// The TOML only holds the appearance; printer, duplex, marks and page number position
// (no closer to the edge than the unprintable area) stay from config/notebook.toml.
export function toInsertFiles(cfg: NotebookConfig): { typ: string; toml: string } {
  const preset = cfg.format.preset;
  const toml = `# Generated by \`just from-web\`. You can edit it by hand; missing
# settings (printer, duplex, marks, page number position) come from config/notebook.toml.
${designToml(cfg, preset, '')}`;
  const typ = toMain(cfg)
    .replace(
      '// Generated by the web generator.',
      '// Generated by `just from-web`. You can edit it by hand.',
    )
    .replace(/sys\.inputs\.at\("title", default: "[^"]*"\)/g, () => typstString(cfg.title))
    .replace(storesInput, () => typstArray(shoppingStores(cfg)));
  // every new piece of user text in sys.inputs needs its own literal here, otherwise in the CLI
  // it would come out empty
  if (typ.includes('sys.inputs')) throw new Error('toInsertFiles: unhandled sys.inputs');
  return { typ, toml };
}

const typstArray = (xs: readonly string[]) =>
  xs.length === 0 ? '()' : `(${xs.map(typstString).join(', ')},)`;

// A Typst string literal (the title in the insert file, which the user edits themselves).
export function typstString(s: string): string {
  const esc = s.replace(
    /[\\"\n\r\t]/g,
    (c) => ({ '\\': '\\\\', '"': '\\"', '\n': '\\n', '\r': '\\r', '\t': '\\t' })[c]!,
  );
  return `"${esc}"`;
}

// default page count of simple inserts in lib/config.typ (must be >= 1)
function insertPages(cfg: NotebookConfig): number {
  return Math.max(1, notesPages(cfg));
}

// Import order doesn't matter; we only import what the enabled sections use.
const IMPORTS: Record<Section['type'], string> = {
  title: '#import "/templates/title.typ": title-page',
  index: '#import "/templates/index.typ": index-page',
  year: '#import "/templates/year.typ": year-page',
  'future-log': '#import "/templates/future-log.typ": future-log-spread',
  months: '#import "/templates/month.typ": month-page',
  weeks: '#import "/templates/week.typ": week-spread',
  daily: '#import "/templates/daily.typ": day-pages',
  habits: '#import "/templates/habits.typ": habit-page',
  budget: '#import "/templates/budget.typ": budget-page',
  todo: '#import "/templates/todo.typ": todo-page',
  cornell: '#import "/templates/cornell.typ": cornell-page',
  travel: '#import "/templates/travel.typ": travel-page',
  reading: '#import "/templates/reading.typ": reading-page',
  notes: '#import "/templates/dot-grid.typ": grid-pages',
  pixels: '#import "/templates/pixels.typ": pixels-page',
  'one-line': '#import "/templates/one-line.typ": one-line-pages',
  birthdays: '#import "/templates/birthdays.typ": birthday-pages',
  packing: '#import "/templates/packing.typ": packing-pages',
  shopping: '#import "/templates/shopping.typ": shopping-pages',
  meals: '#import "/templates/meals.typ": meal-page',
  workout: '#import "/templates/workout.typ": workout-page',
  contacts: '#import "/templates/contacts.typ": contact-page',
  tasting: '#import "/templates/tasting.typ": tasting-page',
  watchlist: '#import "/templates/watchlist.typ": watch-page',
  project: '#import "/templates/project.typ": project-page',
  meeting: '#import "/templates/meeting.typ": meeting-page',
};

// A Typst array of strings; a single-item one needs a comma: ("a",).
const strArray = (xs: readonly string[]) =>
  xs.length === 0 ? '()' : `(${xs.map(str).join(', ')},)`;
const gridArg = (g: string) => (g === 'auto' ? 'auto' : str(g));

const repeat = (n: number, page: string) => `#pages(..range(${n}).map(_ => ${page}))`;

function monthPages(cfg: NotebookConfig, startMonth: number, count: number, fn: string): string {
  const items = Array.from({ length: count }, (_, i) => {
    const [y, m] = monthAt(cfg.year, startMonth, i);
    return `${fn}(year: ${y}, month: ${m})`;
  });
  return `#pages(${items.join(', ')})`;
}

export function sectionBody(cfg: NotebookConfig, s: Section): string {
  switch (s.type) {
    case 'title':
      return `#title-page(title: sys.inputs.at("title", default: ""), owner: ${s.owner})`;
    case 'index':
      return repeat(s.pages, 'index-page()');
    case 'year':
      return '#year-page()';
    case 'future-log':
      return `#future-log-spread(start: ${s.startMonth})`;
    case 'months':
      return monthPages(cfg, s.startMonth, s.count, 'month-page');
    case 'weeks': {
      const [start, end] = weekSpan(cfg.year, s.startWeek, s.count);
      return `#for monday in cal.iso-week-mondays(${cfg.year}).slice(${start - 1}, ${end}) { week-spread(monday) }`;
    }
    case 'daily': {
      const [y, m, d] = parseIsoDate(s.startDate) ?? [cfg.year, 1, 1];
      return `#day-pages(cal.date(${y}, ${m}, ${d}), ${s.count})`;
    }
    case 'habits': {
      const items = Array.from({ length: s.count }, (_, i) => {
        const [y, m] = monthAt(cfg.year, s.startMonth, i);
        return `habit-page(year: ${y}, month: ${m}, habits: ${s.habits})`;
      });
      return `#pages(${items.join(', ')})`;
    }
    case 'budget':
      return monthPages(cfg, s.startMonth, s.count, 'budget-page');
    case 'todo':
      return repeat(s.pages, 'todo-page()');
    case 'cornell':
      return repeat(s.pages, 'cornell-page()');
    case 'travel':
      return repeat(s.pages, 'travel-page()');
    case 'reading':
      return repeat(s.pages, 'reading-page()');
    case 'notes':
      return `#grid-pages(n: ${notesPages(cfg)}, kind: ${gridArg(s.grid)})`;
    case 'pixels':
      return `#pixels-page(year: ${cfg.year}, theme: ${str(s.theme)}, legend: ${s.legend})`;
    case 'one-line':
      return `#one-line-pages(start-month: ${s.startMonth}, months: ${s.count}, years: ${s.years}, per-page: ${s.perPage})`;
    case 'birthdays':
      return `#birthday-pages(per-page: ${s.perPage}, day-column: ${s.dayColumn})`;
    case 'packing':
      return `#packing-pages(groups: ${strArray(s.groups)}, columns: ${s.columns}, pages-count: ${s.pages})`;
    case 'shopping':
      return `#shopping-pages(split: ${str(s.split)}, groups: ${strArray(s.groups)}, stores: ${storesInput}, columns: ${s.columns}, qty: ${s.qty}, pages-count: ${s.pages})`;
    case 'meals':
      return repeat(s.count, `meal-page(meals: ${s.meals}, shopping: ${s.shopping})`);
    case 'workout':
      return repeat(s.pages, `workout-page(kind: ${str(s.kind)})`);
    case 'contacts':
      return repeat(s.pages, `contact-page(fields: ${strArray(s.fields)})`);
    case 'tasting':
      return repeat(
        s.pages,
        `tasting-page(kind: ${str(s.kind)}, per-page: ${s.perPage}, wheel: ${s.wheel})`,
      );
    case 'watchlist':
      return repeat(s.pages, `watch-page(kind: ${str(s.kind)})`);
    case 'project':
      return repeat(s.pages, `project-page(steps: ${s.steps}, kind: ${gridArg(s.grid)})`);
    case 'meeting':
      return repeat(s.pages, `meeting-page(actions: ${s.actions}, kind: ${gridArg(s.grid)})`);
  }
}

// Section start marker: the page is stored in metadata, which the website reads
// with a <nb-section> query to show page ranges and jump to sections.
const marker = (type: string) =>
  `#context [#metadata((type: ${str(type)}, page: here().page())) <nb-section>]`;

// End of content and padding to the volume with grid pages. The last content page
// is marked by <nb-end> (the website reads it too, to show whether the content fits):
// here() in a block with pagebreaks would already point one page further, because a block after a full-page
// grid lands on a new page. For the same reason the first pagebreak is weak
// (the block may already sit on an empty new page). Content longer than the volume is
// only padded to a full signature (a multiple of 4).
const pad = (target: number) => `#context [#metadata((page: here().page())) <nb-end>]
#context {
  let last = query(<nb-end>).first().location().page()
  let pad = if last <= ${target} { ${target} - last } else { calc.rem(4 - calc.rem(last, 4), 4) }
  for i in range(pad) {
    pagebreak(weak: i == 0)
    fill-grid()
  }
}`;

export function toMain(cfg: NotebookConfig): string {
  // notes with no room (0 pages) drop out together with their marker
  const notes = notesPages(cfg);
  const enabled = cfg.sections.filter((s) => s.enabled && (s.type !== 'notes' || notes > 0));
  const imports = [...new Set(enabled.map((s) => IMPORTS[s.type]))];
  const body = enabled.map((s) => `${marker(s.type)}\n${sectionBody(cfg, s)}`);
  return [
    '// Generated by the web generator.',
    '#import "/lib/notebook.typ": *',
    ...imports,
    '',
    '#show: insert.with(title: sys.inputs.at("title", default: "Notes"))',
    '',
    body.join('\n#pagebreak(weak: true)\n'),
    // an empty notebook: a weak padding pagebreak wouldn't fill an empty first page,
    // so the first page gets the grid right away
    body.length ? '' : '#fill-grid()',
    pad(cfg.pages),
    '',
  ].join('\n');
}
